Add contributing guideline and relevant templates
G-Research/spark-dgraph-connector pull request #160
Opened 2022-01-08 08:39 UTC by Debiday

I added the templates into a docs folder to help keep the main repo cleaner. The links to the templates currently give a 404-error, but I've added the correct path and it should work correctly once merged. You can view the templates [here](https://github.com/Debiday/spark-dgraph-connector/tree/contributing-guidelines/docs/templates) I will confirm again if the links work after a merge. Not sure if this workflow is the best, do advise! 😊 Thanks @tpboudreau for the edits.

2022-01-08 08:56 UTC, EnricoMi requested changes
GitHub supports such templates when creating issues, so no need to have issue creator copy anything: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Here is an example (horovod):
- you can choose the template when creating an issue: https://github.com/horovod/horovod/issues/new/choose
- here are the templates: https://github.com/horovod/horovod/tree/master/.github/ISSUE_TEMPLATE
- there is even a pull request template: https://github.com/horovod/horovod/blob/master/.github/pull_request_template.md

2022-01-08 21:55 UTC, Debiday commented
That's awesome!! I didn't realize there was such a tool, okay, let me edit it on Monday.

2022-01-11 20:38 UTC, Debiday commented
Hi @EnricoMi sorry I just had a look at this, and I don't think I have permissions to add templates. Are you able to view the "Issues" or "Features" section? 

If you are, I'll be happy to rework the templates and send them to you. Otherwise, is it possible for me to get temporary permissions to add these templates in? @c-rindi

2022-01-11 21:35 UTC, EnricoMi commented
I have those permissions. But all that it does is adding those template files to `.github/ISSUE_TEMPLATE` and create a pull request like #161. So I presume what you can do is create such a pull request manually that adds those files to that directory. In fact, change this PR to add your templates to `.github/ISSUE_TEMPLATE` rather than `docs/templates`.

2022-01-19 14:25 UTC, EnricoMi commented
Superseded by #161.

2022-01-19 14:25 UTC, closed without merging