Create MAINTAINERS.md
G-Research/spark-dgraph-connector pull request #237
Opened 2023-07-25 10:52 UTC by demarillacizere

The list of maintainers was provided by G-Research OSS.

2023-07-25 11:10 UTC, EnricoMi reviewed
Alistair contributed to this repo, but is he a maintainer? Is he aware of that?

2023-07-25 11:10 UTC, EnricoMi requested changes

2023-07-25 11:10 UTC, EnricoMi commented on MAINTAINERS.md
> +| EnricoMi               | [EnricoMi](https://github.com/EnricoMi)                 |
```suggestion
| Enrico Minack          | [EnricoMi](https://github.com/EnricoMi)                 |
```

2023-07-25 11:17 UTC, demarillacizere commented
> Alistair contributed to this repo, but is he a maintainer? Is he aware of that?

I'm not sure, but I can ask the person in charge at G-Research.

2023-07-26 08:12 UTC, EnricoMi approved these changes
Thanks!

2023-07-26 08:12 UTC, merged